# Generated by Django 3.0.3 on 2020-03-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_item', '0002_auto_20200331_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
